# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='graph_version',
            field=models.IntegerField(default=1),
        ),
    ]
