# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-25 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactor_app', '0002_auto_20170811_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='collaborators',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
