# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactor_app', '0003_project_collaborators'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='save_version',
            field=models.IntegerField(default=1),
        ),
    ]
